Vagrant.configure('2') do |config|
  config.vm.box = 'generic/ubuntu2004'

  $install_script = <<-'SCRIPT'
  sudo apt update -y
  SCRIPT

  ledger_network = '10.250.250'
  ledger_name = 'payments'

  (0..0).each do |i|
    config.vm.define "#{ledger_name}-ca-server-#{i}" do |server|

      server.vm.hostname = "#{ledger_name}-ca-server-#{i}"
      server.vm.network 'private_network', ip: "#{ledger_network}.1#{i}"

      server.vm.provision 'shell', inline: $install_script

      server.vm.provider 'virtualbox' do |vb|
        vb.name = "#{ledger_name}-ca-server-#{i}"
        vb.memory = 2048
        vb.cpus = 1
        vb.customize ['modifyvm', :id, '--nicpromisc2', 'allow-all']
      end
    end
  end

  (0..2).each do |i|
    config.vm.define "#{ledger_name}-orderer-#{i}" do |server|

      server.vm.hostname = "#{ledger_name}-orderer-#{i}"
      server.vm.network 'private_network', ip: "#{ledger_network}.2#{i}"

      server.vm.provision 'shell', inline: $install_script

      server.vm.provider 'virtualbox' do |vb|
        vb.name = "#{ledger_name}-orderer-#{i}"
        vb.memory = 4086
        vb.cpus = 2
        vb.customize ['modifyvm', :id, '--nicpromisc2', 'allow-all']
      end
    end
  end

  (0..1).each do |i|
    config.vm.define "#{ledger_name}-peer-#{i}" do |server|

      server.vm.hostname = "#{ledger_name}-peer-#{i}"
      server.vm.network 'private_network', ip: "#{ledger_network}.3#{i}"

      server.vm.provision 'shell', inline: $install_script

      server.vm.provider 'virtualbox' do |vb|
        vb.name = "#{ledger_name}-peer-#{i}"
        vb.memory = 4086
        vb.cpus = 2
        vb.customize ['modifyvm', :id, '--nicpromisc2', 'allow-all']
      end
    end
  end
end
