Vagrant.configure('2') do |config|
  config.vm.box = 'generic/ubuntu2004'

  $install_script = <<-'SCRIPT'
  sudo apt update -y
  sudo apt install tree sshpass -y
  SCRIPT

  organization01_name = 'bi'
  organization01_network = '10.250.250'

  organization02_name = 'gopay'
  organization02_network = '10.250.251'

  organization03_name = 'dana'
  organization03_network = '10.250.252'

  (0..0).each do |i|
    config.vm.define "#{organization01_name}-ca-server-#{i}" do |server|

      server.vm.hostname = "#{organization01_name}-ca-server-#{i}"
      server.vm.network 'private_network', ip: "#{organization01_network}.1#{i}"

      server.vm.provision 'shell', inline: $install_script

      server.vm.provider 'virtualbox' do |vb|
        vb.name = "#{organization01_name}-ca-server-#{i}"
        vb.memory = 2048
        vb.cpus = 1
        vb.customize ['modifyvm', :id, '--nicpromisc2', 'allow-all']
      end
    end
  end

  (0..2).each do |i|
    config.vm.define "#{organization01_name}-orderer-#{i}" do |server|

      server.vm.hostname = "#{organization01_name}-orderer-#{i}"
      server.vm.network 'private_network', ip: "#{organization01_network}.2#{i}"

      server.vm.provision 'shell', inline: $install_script

      server.vm.provider 'virtualbox' do |vb|
        vb.name = "#{organization01_name}-orderer-#{i}"
        vb.memory = 4086
        vb.cpus = 2
        vb.customize ['modifyvm', :id, '--nicpromisc2', 'allow-all']
      end
    end
  end

  (0..0).each do |i|
    config.vm.define "#{organization02_name}-ca-server-#{i}" do |server|

      server.vm.hostname = "#{organization02_name}-ca-server-#{i}"
      server.vm.network 'private_network', ip: "#{organization02_network}.1#{i}"

      server.vm.provision 'shell', inline: $install_script

      server.vm.provider 'virtualbox' do |vb|
        vb.name = "#{organization02_name}-ca-server-#{i}"
        vb.memory = 2048
        vb.cpus = 1
        vb.customize ['modifyvm', :id, '--nicpromisc2', 'allow-all']
      end
    end
  end

  (0..1).each do |i|
    config.vm.define "#{organization02_name}-peer-#{i}" do |server|

      server.vm.hostname = "#{organization02_name}-peer-#{i}"
      server.vm.network 'private_network', ip: "#{organization02_network}.2#{i}"

      server.vm.provision 'shell', inline: $install_script

      server.vm.provider 'virtualbox' do |vb|
        vb.name = "#{organization02_name}-peer-#{i}"
        vb.memory = 4086
        vb.cpus = 2
        vb.customize ['modifyvm', :id, '--nicpromisc2', 'allow-all']
      end
    end
  end

  (0..0).each do |i|
    config.vm.define "#{organization03_name}-ca-server-#{i}" do |server|

      server.vm.hostname = "#{organization03_name}-ca-server-#{i}"
      server.vm.network 'private_network', ip: "#{organization03_network}.1#{i}"

      server.vm.provision 'shell', inline: $install_script

      server.vm.provider 'virtualbox' do |vb|
        vb.name = "#{organization03_name}-ca-server-#{i}"
        vb.memory = 2048
        vb.cpus = 1
        vb.customize ['modifyvm', :id, '--nicpromisc2', 'allow-all']
      end
    end
  end

  (0..1).each do |i|
    config.vm.define "#{organization03_name}-peer-#{i}" do |server|

      server.vm.hostname = "#{organization03_name}-peer-#{i}"
      server.vm.network 'private_network', ip: "#{organization03_network}.2#{i}"

      server.vm.provision 'shell', inline: $install_script

      server.vm.provider 'virtualbox' do |vb|
        vb.name = "#{organization03_name}-peer-#{i}"
        vb.memory = 4086
        vb.cpus = 2
        vb.customize ['modifyvm', :id, '--nicpromisc2', 'allow-all']
      end
    end
  end
end
